# validate:

listing:
  image: "centos:8.2.2004"
  minimum-packages: 85
  minimum-vulnerabilities: 400

db:
  # new vulnerabilities are added all the time, instead of keeping up it's easier to ignore newer entries.
  # This approach helps tremendously with keeping the analysis relatively stable.
  default-max-year: 2021

  gate:
    # float between 0 and 1, the maximum allowable difference below the OSS F1 score before the gate fails (default 0,
    # meaning the test F1 score must be equal to or greater than the OSS F1 score to pass the gate)
    f1-score-threshold: 0.15

    # float between 0 and 100, the maximum % of unlabeled matches for a scan result before the gate fails (default 10%,
    # meaning the test scan must have less than 10% unlabeled matches to pass the gate)
    unlabeled-matches-threshold: 25.0

    # integer, the maximum allowable introduced FNs by the test scan (but found by the OSS scan) before the gate fails
    # (default 0, meaning the test scan must have the same or fewer FNs than the OSS scan to pass the gate)
    introduced-fns-threshold: 10

  syft:
    # this should match the version of syft that is referenced in vulnerability-match-labels on the main branch.
    # ultimately this is tied to the version of the syft used when building the OCI SBOM cache images hosted on ghcr.io,
    # not the version of syft referenced in the vulnerability-match-labels submodule.
    version: v0.86.1

  # these are the set of images we will capture grype scans for using an existing published DB and a newly build DB.
  # the assumption is that they should perform similarly or the new DB should perform better. We do allow for the new
  # DB to perform slightly worse based on the above gate configuration, but not by much. These images are NOT
  # meant to be exhaustive, but rather a minimum representative sample of images that are represented as namespaces.
  # note: always reference images with BOTH a tag and a digest
  images:
    - docker.io/anchore/test_images:grype-quality-node-d89207b@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4
    - docker.io/anchore/test_images:grype-quality-python-d89207b@sha256:b2b58a55c0b03c1626d2aaae2add9832208b02124dda7b7b41811e14f0fb272c
    - docker.io/anchore/test_images:grype-quality-java-d89207b@sha256:b3534fc2e37943136d5b54e3a58b55d4ccd4363d926cf7aa5bf55a524cf8275b
    - docker.io/anchore/test_images:grype-quality-golang-d89207b@sha256:7536ee345532f674ec9e448e3768db4e546c48220ba2b6ec9bc9cfbfb3b7b74a
    - docker.io/anchore/test_images:grype-quality-ruby-d89207b@sha256:1a5a5f870924e88a6f0f2b8089cf276ef0a79b5244a052cdfe4a47bb9e5a2c10
    - docker.io/anchore/test_images:npm-56d52bc@sha256:ba42ded8613fc643d407a050faf5ab48cfb405ad3ef2015bf6feeb5dff44738d
    - docker.io/anchore/test_images:gems-56d52bc@sha256:5763c8a225f950961bf01ddec68e36f18e236130e182f2b9290a6e03b9777bfe
    - docker.io/anchore/test_images:golang-56d52bc@sha256:d1819e59e89e8ea90073460acb4ebb2ee18ccead9fa880dae91e8fc61b19ca1c
    - docker.io/anchore/test_images:alpine-package-cpe-vuln-match-bd0aaef@sha256:0825acea611c7c5cc792bc7cc20de44d7413fd287dc5afc4aab9c1891d037b4f
    - docker.io/alpine:3.2@sha256:ddac200f3ebc9902fb8cfcd599f41feb2151f1118929da21bcef57dc276975f9
    - docker.io/centos:6@sha256:3688aa867eb84332460e172b9250c9c198fdfd8d987605fd53f246f498c60bcf
    - docker.io/almalinux:8@sha256:cd49d7250ed7bb194d502d8a3e50bd775055ca275d1d9c2785aea72b890afe6a
    - docker.io/rockylinux:8@sha256:72afc2e1a20c9ddf56a81c51148ebcbe927c0a879849efe813bee77d69df1dd8
    - docker.io/oraclelinux:6@sha256:a06327c0f1d18d753f2a60bb17864c84a850bb6dcbcf5946dd1a8123f6e75495
    - docker.io/debian:7@sha256:81e88820a7759038ffa61cff59dfcc12d3772c3a2e75b7cfe963c952da2ad264
    - docker.io/busybox:1.28.1@sha256:2107a35b58593c58ec5f4e8f2c4a70d195321078aebfadfbfb223a2ff4a4ed21
    - docker.io/amazonlinux:2@sha256:1301cc9f889f21dc45733df9e58034ac1c318202b4b0f0a08d88b3fdc03004de
    - registry.access.redhat.com/ubi8@sha256:68fecea0d255ee253acbf0c860eaebb7017ef5ef007c25bee9eeffd29ce85b29
    - cgr.dev/chainguard/wolfi-base:latest-20221001@sha256:be3834598c3c4b76ace6a866edcbbe1fa18086f9ee238b57769e4d230cd7d507
    - ghcr.io/chainguard-images/scanner-test@sha256:59bddc101fba0c45d5c093575c6bc5bfee7f0e46ff127e6bb4e5acaaafb525f9
    - mcr.microsoft.com/cbl-mariner/base/core:2.0.20220731-arm64@sha256:51101e635f56032d5afd3fb56d66c7b93b34d5a39ddac01695d62b94473cc34e
    - docker.io/ubuntu:20.04@sha256:9d42d0e3e57bc067d10a75ee33bdd1a5298e95e5fc3c5d1fce98b455cb879249