# this configuration is intended to be used for ad-hoc builds of the database to the staging environment

data: !include config/grype-db-manager/include.d/data.yaml

grype-db: !include config/grype-db-manager/include.d/grype-db-local-build.yaml

distribution: !include config/grype-db-manager/include.d/distribution-staging.yaml

validate: !include config/grype-db-manager/include.d/validate.yaml
