# runs-on.com runner configuration for grype-db

runners:

  # DATA SYNC RUNNERS ################################################################################################

  # grype-db-pull: standard runners for lightweight vulnerability data providers
  # - providers with small workspace footprints (< 1GB)
  # - I/O-light workloads (alpine, debian, github, etc.)
  grype-db-pull: &grype-db-pull
    cpu: 8
    ram: [16, 32]
    spot: price-capacity-optimized
    extras: s3-cache
    family:
      # runson family --cpu=8 --mem="16:32" --budget=0.5 -o yaml --globs
      # /cpu=8/ram=16+32/family=c5+c6+c7+m5+m6+m7+t3+t4
      - "t4*"  # burstable, arm64, 8 CPU, 32GB, EBS:695Mbps, $0.27/hr
      - "c6*"  # compute, amd64/arm64/x86_64, 8 CPU, 16GB, NVMe:474GB, $0.27-$0.45/hr
      - "c7*"  # compute, amd64/arm64/x86_64, 8 CPU, 16GB, NVMe:474GB, $0.29-$0.50/hr
      - "t3*"  # burstable, amd64/x86_64, 8 CPU, 32GB, EBS:695Mbps, $0.30-$0.33/hr
      - "c5*"  # compute, amd64/x86_64, 8 CPU, 16-21GB, NVMe:200-300GB, $0.31-$0.43/hr
      - "m6*"  # general, amd64/arm64/x86_64, 8 CPU, 32GB, NVMe:474GB, $0.31-$0.47/hr
      - "m7*"  # general, amd64/arm64/x86_64, 8 CPU, 32GB, NVMe:474GB, $0.33-$0.46/hr
      - "m5*"  # general, amd64/x86_64, 8 CPU, 32GB, NVMe:300GB, $0.34-$0.48/hr

  # grype-db-pull-large: NVMe-backed runners for I/O-heavy vulnerability data providers
  # - providers with large workspace footprints (NVD ~25GB, RHEL ~7GB, etc.)
  # - cache extraction and data processing are I/O-bound
  # - local NVMe storage avoids EBS throughput limits for random I/O
  # - spot: false to avoid interruptions on long-running syncs
  grype-db-pull-large: &grype-db-pull-large
    cpu: 8
    ram: [16, 64]
    spot: false
    extras: s3-cache
    family:
      # runson family --cpu=8 --mem="16:64" --budget=0.7 --local-nvme -o yaml --globs
      # /cpu=8/ram=16+64/family=c5ad+c5d+c6gd+c6id+c7gd+m5ad+m5d+m6gd+m6id+m7gd+r5ad+r5d+r6gd+r6id+r7gd
      - "c6gd*"  # compute, arm64, 8 CPU, 16GB, NVMe:474GB, $0.31/hr
      - "c5ad*"  # compute, amd64, 8 CPU, 16GB, NVMe:300GB, $0.34/hr
      - "m6gd*"  # general, arm64, 8 CPU, 32GB, NVMe:474GB, $0.36/hr
      - "c7gd*"  # compute, arm64, 8 CPU, 16GB, NVMe:474GB, $0.36/hr
      - "c5d*"   # compute, x86_64, 8 CPU, 16GB, NVMe:200GB, $0.38/hr
      - "c6id*"  # compute, x86_64, 8 CPU, 16GB, NVMe:474GB, $0.40/hr
      - "m5ad*"  # general, amd64, 8 CPU, 32GB, NVMe:300GB, $0.41/hr
      - "m7gd*"  # general, arm64, 8 CPU, 32GB, NVMe:474GB, $0.43/hr
      - "m5d*"   # general, x86_64, 8 CPU, 32GB, NVMe:300GB, $0.45-$0.54/hr
      - "r6gd*"  # memory, arm64, 8 CPU, 64GB, NVMe:474GB, $0.46/hr
      - "m6id*"  # general, x86_64, 8 CPU, 32GB, NVMe:474GB, $0.47-$0.64/hr
      - "r5ad*"  # memory, amd64, 8 CPU, 64GB, NVMe:300GB, $0.52/hr
      - "r7gd*"  # memory, arm64, 8 CPU, 64GB, NVMe:474GB, $0.54/hr
      - "r5d*"   # memory, x86_64, 8 CPU, 64GB, NVMe:300GB, $0.58-$0.67/hr
      - "r6id*"  # memory, x86_64, 8 CPU, 64GB, NVMe:474GB, $0.60/hr

  # grype-db-pull-multicore: high-CPU runners for concurrency-heavy providers
  # - providers that benefit from parallel processing (ubuntu)
  # - 16 CPUs for concurrent vulnerability data fetching/processing
  grype-db-pull-multicore: &grype-db-pull-multicore
    cpu: 16
    ram: [32, 64]
    spot: price-capacity-optimized
    extras: s3-cache
    family:
      # runson family --cpu=16 --mem=64 --budget=1.0 -o yaml --globs
      # /cpu=16/ram=64/family=m5+m6+m7
      - "m6*"  # general, amd64/arm64/x86_64, 16 CPU, 64GB, NVMe:950GB, $0.62-$0.95/hr
      - "m7*"  # general, amd64/arm64/x86_64, 16 CPU, 64GB, NVMe:950GB, $0.65-$0.93/hr
      - "m5*"  # general, amd64/x86_64, 16 CPU, 64GB, NVMe:600GB, $0.69-$0.95/hr
