root: ./data/vunnel

log:
  slim: true
  level: debug

providers:
  ubuntu:
    # there is a lot of IO when running git log commands in this provider, so some concurrency helps here
    # increased to 64 to match the 32-CPU runner used in daily-data-sync (2x oversubscription for I/O bound work)
    max_workers: 64

  nvd:
    # apply community-provided overrides to the NVD data
    # sourced from the https://github.com/anchore/nvd-data-overrides repo
    overrides_enabled: true

    # we're getting a lot of 503s and intermittent failures from the NVD API, so we're going to retry a few times
    request_timeout: 125
    request_retry_count: 15
    runtime:
      on_error:
        retry_count: 10
        retry_delay: 60