name: "Download listing file and db"

on:
  schedule:
    - cron: "*/30 * * * *" # run every 30 minutes
  workflow_dispatch:

jobs:
  Download-listing-and-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - run: .github/scripts/download-listing-and-db.sh
