name: 'Fix v5 listing'
on:
  # allow for kicking off DB builds manually
  workflow_dispatch:
    inputs:
      publish-databases:
        description: "build new databases and upload to S3"
        type: boolean
        required: true
        default: true
      publish-listing:
        description: "use S3 state to update and publish listing file"
        type: boolean
        required: true
        default: true

  # run 4 AM (UTC) daily
  schedule:
    - cron:  '0 4 * * *'

env:
  CGO_ENABLED: "0"
  SLACK_NOTIFICATIONS: true
  FORCE_COLOR: true

jobs:

  publish-listing-file:
    name: "Publish listing file"
    runs-on: ubuntu-22.04-4core-16gb
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          submodules: true

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Publish listing file
        run: |
          uv run \
            grype-db-manager \
              -c ./config/grype-db-manager/publish-production-r2.yaml \
                listing update
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLBOX_CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLBOX_CLOUDFLARE_SECRET_ACCESS_KEY }}
          GRYPE_DB_MANAGER_DISTRIBUTION_S3_ENDPOINT_URL: ${{ secrets.TOOLBOX_CLOUDFLARE_R2_ENDPOINT }}

      - uses: 8398a7/action-slack@28ba43ae48961b90635b50953d216767a6bea486 #v3.16.2
        with:
          status: ${{ job.status }}
          fields: workflow,eventName,job
          text: Publishing the Grype DB listing file has failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOOLBOX_WEBHOOK_URL }}
        if: ${{ failure() && env.SLACK_NOTIFICATIONS == 'true' }}

  sync-listing-file-to-s3:
    name: "Sync listing file to S3"
    needs:
      - publish-listing-file
    uses: ./.github/workflows/copy-listing-from-r2.yaml
    secrets: inherit
