name: "Release"

permissions: {}

# there should never be two releases in progress at the same time
concurrency:
  group: release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      version:
        description: tag the latest commit on main with the given version (prefixed with v)
        required: true

jobs:

  version-available:
    uses: anchore/workflows/.github/workflows/check-version-available.yaml@b3e328b5ae31ba96297e2ed9a6124e5e6352a4c5 # v0.7.0
    with:
      version: ${{ github.event.inputs.version }}

  check-gate:
    permissions:
      checks: read   # required for getting the status of specific check names
    uses: anchore/workflows/.github/workflows/check-gate.yaml@b3e328b5ae31ba96297e2ed9a6124e5e6352a4c5 # v0.7.0
    with:
      # these are checks that should be run on pull-request and merges to main.
      # we do NOT want to kick off a release if these have not been verified on main.
      # Please see the validations.yaml workflow for the names that should be used here.
      checks: '["Build snapshot artifacts", "CLI tests (Go-Linux)", "CLI tests (Python)", "DB acceptance tests", "Discover supported schema versions", "Static analysis", "Unit tests (Go)", "Unit tests (Python)"]'

  release:
    needs: [check-gate, version-available]
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          # we need to persist credentials so that we can push the tag
          persist-credentials: true
          fetch-depth: 0

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap
        with:
          # use the same cache we used for building snapshots
          build-cache-key-prefix: "snapshot"
          python: false

      - name: Tag release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git tag $VERSION
          git push origin --tags

      - name: Build release artifacts
        run: make ci-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
